{{- if .Values.ingress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "nodejs.fullname" . }}
  annotations:
    {{- range $key, $value := .Values.ingress.annotations }}
    {{ $key }}: {{ $value }}
    {{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.hosts }}
      http:
        paths:
          - path: {{ .Values.ingress.path }}/?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "nodejs.fullname" . }}
                port:
                  number: {{ .Values.service.port }}
{{- end -}}

